version: 5.1.0
variant: cyberpunk
logo: /img/favicon.ico
head:
  favicon: /img/favicon.ico
  manifest:
    name:
    short_name:
    start_url:
    theme_color:
    background_color:
    display: standalone
    icons:
      - src: ""
        sizes: ""
        type:
  open_graph:
    title:
    type: blog
    url:
    image:
    site_name:
    author: xeonds
    description:
    twitter_card:
    twitter_id:
    twitter_site:
    google_plus:
    fb_admins:
    fb_app_id:
  structured_data:
    title:
    description:
    url:
    author:
    publisher:
    publisher_logo:
    image:
  meta:
    - ""
  rss: /atom.xml
navbar:
  menu:
    Home: /
    Archive: /archives
    Category: /categories
    Link: /links
    About: /about
  links:
    My GitHub:
      icon: fab fa-github
      url: https://github.com/xeonds
footer:
  links:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution 4.0 International:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    Download on GitHub:
      icon: fab fa-github
      url: https://github.com/ppoffice/hexo-theme-icarus
article:
  highlight:
    theme: atom-one-light
    clipboard: true
    fold: unfolded
  readtime: true
  update_time: true
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    Noncommercial:
      icon: fab fa-creative-commons-nc
      url: https://creativecommons.org/licenses/by-nc/4.0/
search:
  type: insight
  index_pages: true
comment:
  type: gitalk
  client_id: 2bfc40bc0b5fef7b0688
  client_secret: 475f278f70ff3f0888e047f10766ab6929168f78
  repo: xeonds.github.io
  owner: xeonds
  admin:
    - xeonds
  per_page: 20 # 可选填
  distraction_free_mode: false
  pager_direction: last
  create_issue_manually: false
  proxy:
  flip_move_options: # 可选填
  enable_hotkey: true # 可选填
  language: zh-CN # 可选填
# donates:
#     -
#         type: afdian
#         url: ''
#     -
#         type: alipay
#         qrcode: ''
#     -
#         type: buymeacoffee
#         url: ''
#     -
#         type: patreon
#         url: ''
#     -
#         type: paypal
#         business: ''
#         currency_code: USD
#     -
#         type: wechat
#         qrcode: ''
share:
  type: sharethis
  install_url: "https://mxts.jiujiuer.xyz/"
sidebar:
  left:
    sticky: false
  right:
    sticky: false
widgets:
  - position: left
    type: profile
    author: xeonds
    author_title: "ENJ0Y CREATiNG."
    location: Solaris, Earth
    avatar: /img/avatar.jpg
    avatar_rounded: false
    gravatar:
    follow_link: https://github.com/xeonds
    social_links:
      Github:
        icon: fab fa-github
        url: https://github.com/xeonds
      # Facebook:
      #     icon: fab fa-facebook
      #     url: https://facebook.com
      # Twitter:
      #     icon: fab fa-twitter
      #     url: https://twitter.com/xeonds
      # Dribbble:
      #     icon: fab fa-dribbble
      #     url: https://dribbble.com
      RSS:
        icon: fas fa-rss
        url: /atom.xml
  - position: left
    type: toc
    index: true
  - position: left
    type: links
    links:
      Holynia: https://holynia.github.io
      Ray: https://ray.al
      Robotxm: https://moefactory.com
      Dimole: https://blog.dml.ink
      All: https://mxts.jiujiuer.xyz/links
    # - position: left
    # type: categories
  - position: right
    type: recent_posts
  - position: right
    type: archives
  # - position: right
  #   type: tags
  #   collapsed: true
  #   order_by: name
  #   amount:
  #   show_count: true
  # -
  #     position: left
  #     type: subscribe_email
  #     description:
  #     feedburner_id: ''
  # -
  #     position: left
  #     type: adsense
  #     client_id: ''
  #     slot_id: ''
  # -
  #     position: left
  #     type: followit
  #     description:
  #     action_url: ''
  #     verification_code: ''
plugins:
  animejs: true
  back_to_top: true
  baidu_analytics:
    tracking_id: 59fd9f709f6626bf608f0b08415e0283
  bing_webmaster:
    tracking_id:
  busuanzi: true
  cnzz:
    id:
    web_id:
  cookie_consent:
    type: info
    theme: edgeless
    static: false
    position: bottom-left
    policyLink: https://www.cookiesandyou.com/
  gallery: true
  google_analytics:
    tracking_id:
  hotjar:
    site_id:
  katex: false
  mathjax: true
  outdated_browser: false
  progressbar: true
  statcounter:
    project:
    security:
  twitter_conversion_tracking:
    pixel_id:
providers:
  cdn: jsdelivr
  fontcdn: google
  iconcdn: fontawesome
auto_excerpt:
  enable: true
  length: 150
